Make CDI converter/validator compatible with Tomcat. It crashed with NoClassDefFoundError on a CDI specific class during OmniApplication#createXxx() once a custom converter or validator is added to the project. Solution was to detach CDI from JSF by creating an abstract provider.